version: "3.8"

services:
  graphql-schema-diff:
    build:
      context: .
    image: graphql-schema-diff:1
    container_name: graphql-schema-diff
    restart: unless-stopped
    networks:
      - open
    env_file:
      - .env
    volumes:
      - ./data:/data
    working_dir: /app
    command: main.py

networks:
  open:
    external: true
